version: '3'

services:
  mysql2:
    container_name: mysql2
    image: mysql:latest
    ports:
      - "3308:3306"
    restart: always
    environment:
      MYSQL_DATABASE: tab
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: tab
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  backend:
    build: .
    container_name: backend
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql2:3306/tab
      SPRING_DATASOURCE_USER: tab
      SPRING_DATASOURCE_PASSWORD: tab
    depends_on:
      - mysql2