spring:
  datasource:
    include:
     - docker
#      - local

  jpa:
    hibernate:
      ddl-auto : validate  # 스테이징, 운영 환경에서는 create, create-drop, update는 사용하지 말것
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true    # 실행되는 JPQL을 보고싶다면 다음과 같이 추가한다.
    show_sql: true

logging:
  level:
    org:
      hibernate: info