spring:
  # local 실행 시
  profiles:
    default: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/tab?useSSL=false
    username: root
    password: tab

  jpa:
    hibernate:
      ddl-auto : create
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    org:
      hibernate: info

