spring:
  datasource:
    include:
      - docker
#      - local

  jpa:
    hibernate:
      ddl-auto : create
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
    show_sql: true

logging:
  level:
    org:
      hibernate: info

