spring:
  datasource:
    include:
#     - docker
      - local

  jpa:
    hibernate:
      ddl-auto : create
<<<<<<< HEAD
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
=======
>>>>>>> 4719b56aa861c1ae6ed95a34390651458402cba0
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true    # 실행되는 JPQL을 보고싶다면 다음과 같이 추가한다.
    show_sql: true

logging:
  level:
    org:
      hibernate: info